import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ContextProvider } from "@/contexts/ContextProvider";
import Notifications from "@/components/Notification";
import Footer from "@/components/Footer";
import AppBar from "@/components/AppBar";
import "@solana/wallet-adapter-react-ui/styles.css";
import { ToastProvider } from "@heroui/toast";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ContextProvider>
          {/* <Notifications /> */}
          <AppBar/>
          <ToastProvider placement="top-center"/>
          {children}
          <Footer/>
        </ContextProvider>

        <script src="assets/libs/preline/preline.js"></script>
        <script src="assets/libs/swiper/swiper-bundle.min.js"></script>
        <script src="assets/libs/gumshoe/gumshoe.polyfills.min.js"></script>
        <script src="assets/libs/lucide/lucide.min.js"></script>
        <script src="assets/libs/aos/aos.js"></script>
        <script src="assets/js/swiper.js"></script>
        <script src="assets/js/theme.js"></script>
      </body>
    </html>
  );
}
